[project]
name = "sql-agent"
version = "0.1.0"
authors = [
    { name = "Wael Lejmi", email = "wael.lejmi02@gmail.com" }
]
description = "Agent to transform human messages to sql requests , then can execute them and return the results to the user"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docker>=7.0.0",
    "httpx>=0.28.1",
    "langchain>=1.2.10",
    "langchain-community>=0.4.1",
    "langchain-groq>=1.1.2",
    "langgraph>=1.0.8",
    "mcp[cli]>=1.26.0",
    "python-dotenv>=1.2.1",
    "sqlglot>=29.0.1",
]



[project.optional-dependencies]
embedding = [    
    "pyyaml>=6.0.2",
    "sentence-transformers>=5.1.1",
]
all = [
    "psycopg2-binary>=2.9.0",
    "PyMySQL>=1.1.0",
]
postgres = ["psycopg2-binary>=2.9.0"]
mysql = ["PyMySQL>=1.1.0"]
mariadb = ["PyMySQL>=1.1.0"]
oracle= ["oracledb>=2.0.0"]
#TODO: Wait for SQLalchemy 2.1 support for mssql-python, it already merged 
# https://github.com/microsoft/mssql-python#installation
# mssql ["mssql-python>=X.X.X"]
mssql = ["pymssql >= 2.3.11"]

mssql-native = ["pyodbc>=5.1.0"]
mysql-native = ["mysqlclient>=2.2.8"]
mariadb-native = ["mariadb>=1.1.0"]

cockroachdb = ["psycopg2-binary>=2.9.0"]
ssh = [ "sshtunnel>=0.4.0",
    "paramiko>=2.0.0,<4.0.0",
]


[dependency-groups]
dev = []


