services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: northwind-mssql
    platform: linux/amd64

    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: NorthwindPass123!
      MSSQL_PID: Developer

    labels:
      - "db.name=Northwind"

    ports:
      - "${MSSQL_PORT:-1433}:1433"

    tmpfs:
      - /var/opt/mssql:rw,uid=10001,gid=0

    volumes:
      - ../../data/instnwnd.sql:/scripts/instnwnd.sql

    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools18/bin/sqlcmd",
          "-S",
          "localhost",
          "-U",
          "sa",
          "-P",
          "NorthwindPass123!",
          "-C",
          "-Q",
          "SELECT 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 10s

    command: >
      bash -c '
      /opt/mssql/bin/sqlservr &

      until /opt/mssql-tools18/bin/sqlcmd \
        -S localhost \
        -U sa \
        -P "$$MSSQL_SA_PASSWORD" \
        -C \
        -Q "SELECT 1" > /dev/null 2>&1;
      do
        sleep 2;
      done;

      /opt/mssql-tools18/bin/sqlcmd \
        -S localhost \
        -U sa \
        -P "$$MSSQL_SA_PASSWORD" \
        -C \
        -Q "CREATE DATABASE Northwind";

      /opt/mssql-tools18/bin/sqlcmd \
        -S localhost \
        -U sa \
        -P "$$MSSQL_SA_PASSWORD" \
        -d Northwind \
        -C \
        -i /scripts/instnwnd.sql;

      wait
      '

